# Generated by Django 5.1.3 on 2024-11-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(max_length=30)),
                ('balance_pesos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_dolares', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_pago', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='finanzas.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_prestado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pago_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='finanzas.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('tipo_tarjeta', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=3)),
                ('expiracion', models.DateField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='finanzas.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descripcion', models.TextField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='finanzas.cuenta')),
            ],
        ),
    ]
