# Generated by Django 5.1.3 on 2024-11-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pago',
            new_name='Servicios',
        ),
    ]
