# Generated by Django 5.1.3 on 2024-11-27 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_remove_transferencia_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='meses_duracion',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
