# Generated by Django 5.1.3 on 2024-11-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_prestamo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=20),
        ),
    ]
