# Generated by Django 5.1.3 on 2024-11-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_tarjeta_cvv_alter_tarjeta_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='proveedor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
