# Generated by Django 5.1.3 on 2024-12-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_alter_tarjeta_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo_cuenta',
            field=models.CharField(choices=[('ahorro', 'Ahorro'), ('corriente', 'Corriente')], max_length=30),
        ),
    ]
