# Generated by Django 5.1.3 on 2024-12-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_cuenta_numero_cuenta_alter_cuenta_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='activo', max_length=10),
        ),
    ]
