# Generated by Django 5.1.3 on 2024-12-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0010_cuenta_numero_cuenta_alter_cuenta_tipo_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='estado',
            field=models.CharField(default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
    ]
