# Generated by Django 5.1.3 on 2024-12-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_servicios_estado_alter_servicios_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
