# Generated by Django 5.1.3 on 2024-12-04 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_alter_prestamo_estado'),
        ('finanzas', '0012_alter_servicios_fecha_pago'),
    ]

    operations = [
    ]
