# Generated by Django 5.1.3 on 2024-12-05 06:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_merge_20241203_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='username_emisor',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferencia',
            name='username_receptor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='cuenta_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='finanzas.cuenta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='cuenta_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origen', to='finanzas.cuenta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
